Journey-Together/Server

build.gradle
src/main/java/Journey/Together/domain/place/controller/PlaceController.java
src/main/java/Journey/Together/domain/place/dto/response/MainRes.java
src/main/java/Journey/Together/domain/place/dto/response/PlaceDetailRes.java
src/main/java/Journey/Together/domain/place/dto/response/PlaceRes.java
src/main/java/Journey/Together/domain/place/dto/response/PlaceReviewDto.java
src/main/java/Journey/Together/domain/place/entity/DisabilityCategory.java
src/main/java/Journey/Together/domain/place/entity/DisabilityPlaceCategory.java
src/main/java/Journey/Together/domain/place/entity/DisabilitySubCategory.java
src/main/java/Journey/Together/domain/place/entity/DisabilitySubCategoryRepository.java
src/main/java/Journey/Together/domain/place/entity/Place.java
src/main/java/Journey/Together/domain/place/repository/DisabilityPlaceCategoryRepository.java
src/main/java/Journey/Together/domain/place/repository/PlaceRepository.java
src/main/java/Journey/Together/domain/place/service/PlaceService.java
src/main/java/Journey/Together/domain/placeBookbark/entity/PlaceBookmark.java
src/main/java/Journey/Together/domain/placeBookbark/repository/PlaceBookmarkRepository.java
src/main/java/Journey/Together/domain/placeReview/entity/PlaceReview.java
src/main/java/Journey/Together/domain/placeReview/entity/PlaceReviewImg.java
src/main/java/Journey/Together/global/exception/ErrorCode.java
src/main/java/Journey/Together/global/exception/Success.java

- close #20 
아직 리뷰쪽을 못해서 일단 reviewList는 null 값으로 넣어놨습니다. 추후 변경하겠습니다.
예외처리 생각을 많이 못했는데 일단 급하니 올리고 나중에 리팩하는쪽으로....
이것도 쿼리 나중에 변경하겠습니다!!
- baseurl/place/{placeId}

[Feat/#20] 관광정보 상세보기 api

---

src/main/java/Journey/Together/domain/member/controller/MyPageController.java
src/main/java/Journey/Together/domain/member/dto/MyPageRes.java
src/main/java/Journey/Together/domain/member/service/MemberService.java

- close #24 
아직 리뷰쪽이 완성이 안되어서 일단 리뷰개수 0으로 정적으로 박아놨습니다.
추후 리뷰쪽 개발완료되면 로직 변경하겠습니다
- ~/v1/mypage

[Feat/#24] 마이페이지 기본정보

---

src/main/java/Journey/Together/domain/member/service/AuthService.java
src/main/java/Journey/Together/domain/member/service/MemberService.java

member.getProfileUrl->member.getProfileUuid으로 변경

fix : 오류 수정

---

src/main/java/Journey/Together/domain/dairy/controller/PlanController.java
src/main/java/Journey/Together/domain/dairy/dto/DailyPlace.java
src/main/java/Journey/Together/domain/dairy/dto/DaliyPlace.java
src/main/java/Journey/Together/domain/dairy/dto/PlanReq.java
src/main/java/Journey/Together/domain/dairy/entity/Day.java
src/main/java/Journey/Together/domain/dairy/entity/Plan.java
src/main/java/Journey/Together/domain/dairy/repository/DayRepository.java
src/main/java/Journey/Together/domain/dairy/repository/PlanRepository.java
src/main/java/Journey/Together/domain/dairy/service/PlanService.java
src/main/java/Journey/Together/domain/member/service/MemberService.java
src/main/java/Journey/Together/domain/place/repository/PlaceRepository.java
src/main/java/Journey/Together/global/exception/Success.java

feat : 여행 일정 등록 api 구현

---

src/main/java/Journey/Together/domain/dairy/controller/PlanController.java
src/main/java/Journey/Together/domain/dairy/dto/PlaceInfo.java
src/main/java/Journey/Together/domain/dairy/dto/PlaceInfoPageRes.java
src/main/java/Journey/Together/domain/dairy/service/PlanService.java
src/main/java/Journey/Together/domain/place/repository/PlaceRepository.java

- close #34
장소 이름 기반으로 검색하였습니다.
장소 createdAt 기준으로 나열하였습니다
-

#34 feat : 일정 정보 저장시 장소 검색 api

---

src/main/java/Journey/Together/domain/dairy/controller/PlanController.java
src/main/java/Journey/Together/domain/dairy/dto/PlanRes.java
src/main/java/Journey/Together/domain/dairy/service/PlanService.java
src/main/java/Journey/Together/global/exception/Success.java

#35 feat : 일정 후기 후기 작성 시 상단에 뜨는 일정 정보 api

---

src/main/java/Journey/Together/domain/dairy/controller/PlanController.java
src/main/java/Journey/Together/domain/dairy/dto/DailyList.java
src/main/java/Journey/Together/domain/dairy/dto/DailyPlaceInfo.java
src/main/java/Journey/Together/domain/dairy/dto/PlanDetailRes.java
src/main/java/Journey/Together/domain/dairy/repository/DayRepository.java
src/main/java/Journey/Together/domain/dairy/repository/PlanRepository.java
src/main/java/Journey/Together/domain/dairy/service/PlanService.java
src/main/java/Journey/Together/domain/place/repository/DisabilitySubCategoryRepository.java

- close #43 
List<String> imageUrls 을 처리하는 부분에서 잘 처리되었는지 확인 부탁드립니다 
List<Day>를 사용하는 구간이 많았는데 잘 사용했는지 궁금합니다.
샷
-

feat : 일정 상세보기 api 구현

---

src/main/java/Journey/Together/domain/place/controller/PlaceController.java
src/main/java/Journey/Together/domain/place/dto/response/PlaceBookmarkDto.java
src/main/java/Journey/Together/domain/place/service/PlaceService.java
src/main/java/Journey/Together/domain/placeBookbark/entity/PlaceBookmark.java
src/main/java/Journey/Together/domain/placeBookbark/repository/PlaceBookmarkRepository.java
src/main/java/Journey/Together/global/exception/Success.java

- close #50 
- ~/v1/place/bookmark

[#50] feat: 북마크한 여행지 이름가져오기

---

src/main/java/Journey/Together/domain/place/controller/PlaceController.java
src/main/java/Journey/Together/domain/place/service/PlaceService.java
src/main/java/Journey/Together/domain/placeBookbark/entity/PlaceBookmark.java
src/main/java/Journey/Together/domain/placeBookbark/repository/PlaceBookmarkRepository.java
src/main/java/Journey/Together/global/exception/Success.java

- close #52 
- ~/v1/place/bookmark/{placeId}

[#52] feat: 북마크 상태 변경

---

src/main/java/Journey/Together/domain/bookbark/controller/BookmarkController.java
src/main/java/Journey/Together/domain/bookbark/dto/PlaceBookmarkRes.java
src/main/java/Journey/Together/domain/bookbark/entity/PlaceBookmark.java
src/main/java/Journey/Together/domain/bookbark/entity/PlanBookmark.java
src/main/java/Journey/Together/domain/bookbark/entity/PlanBookmarkRes.java
src/main/java/Journey/Together/domain/bookbark/repository/PlaceBookmarkRepository.java
src/main/java/Journey/Together/domain/bookbark/repository/PlanBookmarkRepository.java
src/main/java/Journey/Together/domain/bookbark/service/BookmarkService.java
src/main/java/Journey/Together/domain/place/controller/PlaceController.java
src/main/java/Journey/Together/domain/place/dto/response/PlaceBookmarkDto.java
src/main/java/Journey/Together/domain/place/service/PlaceService.java
src/main/java/Journey/Together/global/exception/Success.java

- close #54 
- ~/v1/bookmark/plan
- ~/v1/bookmark/place

[Feat/#54] 북마크한 장소 및 일정보기

---

src/main/java/Journey/Together/domain/member/service/MemberService.java
src/main/java/Journey/Together/global/util/S3Client.java

사용자 이미지 수정 시 s3에서 update로 수정
```java
결과 예시 사진 첨부
```
-

fix : profile update

---

src/main/java/Journey/Together/domain/dairy/dto/OpenPlanRes.java
src/main/java/Journey/Together/domain/dairy/dto/PlanDetailRes.java
src/main/java/Journey/Together/domain/dairy/service/PlanService.java
src/main/java/Journey/Together/domain/member/controller/AuthController.java
src/main/java/Journey/Together/domain/member/dto/LoginReq.java
src/main/java/Journey/Together/domain/member/dto/LoginRes.java
src/main/java/Journey/Together/domain/member/dto/MemberReq.java
src/main/java/Journey/Together/domain/member/dto/MemberRes.java
src/main/java/Journey/Together/domain/member/entity/Member.java
src/main/java/Journey/Together/domain/member/service/AuthService.java
src/main/java/Journey/Together/domain/member/service/MemberService.java
src/main/java/Journey/Together/domain/place/dto/response/PlaceReivewListDto.java
src/main/java/Journey/Together/global/security/kakao/KakaoClient.java
src/main/java/Journey/Together/global/security/kakao/dto/KakaoProfile.java

- close #
name->nickname 변경 및 kakao nickname 받아 올 수 있도록 구현
name->nickname 잘 변경 했는지 확인 부탁드려요
-

fix : name->nickname 변경

---

src/main/java/Journey/Together/domain/dairy/controller/PlanController.java
src/main/java/Journey/Together/domain/dairy/service/PlanService.java

- close #31 
```java
결과 예시 사진 첨부
```
- /v1/plan/{planId}/ispublic

feat : 일정 공개/비공개 수정 api 구현

---

src/main/java/Journey/Together/global/security/kakao/KakaoClient.java

- close #
```java
결과 예시 사진 첨부
```
-

fix : delete unlink

---

src/main/java/Journey/Together/domain/dairy/controller/PlanController.java
src/main/java/Journey/Together/domain/dairy/entity/PlanReviewImage.java
src/main/java/Journey/Together/domain/dairy/repository/PlanReviewImageRepository.java
src/main/java/Journey/Together/domain/dairy/repository/PlanReviewRepository.java
src/main/java/Journey/Together/domain/dairy/service/PlanService.java
src/main/java/Journey/Together/global/exception/Success.java
src/main/java/Journey/Together/global/util/S3Client.java

- #31 
일정 후기 데이터, 후기 이미지 데이터, s3에 저장된 이미지들 삭제
- v1/plan/review/{reviewId}

#31 feat : 일정 후기 삭제 api

---

src/main/java/Journey/Together/domain/place/controller/PlaceController.java
src/main/java/Journey/Together/domain/place/dto/request/UpdateReviewDto.java
src/main/java/Journey/Together/domain/place/repository/PlaceRepositoryCustom.java
src/main/java/Journey/Together/domain/place/repository/PlaceRepositoryImpl.java
src/main/java/Journey/Together/domain/place/repository/PlaceReviewImgRepository.java
src/main/java/Journey/Together/domain/place/service/PlaceService.java
src/main/java/Journey/Together/global/exception/Success.java

- close #56 
이미지 삭제할때 이미지 url을 받아서 삭제했는데 보통 이미지 삭제시 그런식으로 하는지...?
- ~/v1/place/review/my/{reviewId}

[Feat/#56] 여행지 수정 api

---

src/main/java/Journey/Together/domain/bookbark/controller/BookmarkController.java
src/main/java/Journey/Together/domain/bookbark/repository/PlanBookmarkRepository.java
src/main/java/Journey/Together/domain/bookbark/service/BookmarkService.java
src/main/java/Journey/Together/domain/dairy/repository/PlanRepository.java

- close #65 
나의 일정에도 북마크 가능한가?-> 일단 가능하다고 처리
- ~/v1/bookmark/plan/{planId}

[#65] feat: 일정 북마크 상태변경

---

src/main/java/Journey/Together/domain/bookbark/entity/PlanBookmarkRes.java
src/main/java/Journey/Together/domain/bookbark/service/BookmarkService.java

- close #67 
- ~/v1/bookmark/plan

[Feat/#67] nickname 및 이미지 url 수정

---

src/main/java/Journey/Together/domain/dairy/dto/PlanDetailRes.java
src/main/java/Journey/Together/domain/dairy/service/PlanService.java

- close #71 
```java
결과 예시 사진 첨부
```
-

fix : isPublic false로 고정

---

src/main/java/Journey/Together/domain/place/dto/response/PlaceDetailGuestRes.java
src/main/java/Journey/Together/domain/place/dto/response/PlaceDetailRes.java
src/main/java/Journey/Together/domain/place/dto/response/PlaceReviewDto.java
src/main/java/Journey/Together/domain/place/dto/response/SubDisability.java
src/main/java/Journey/Together/domain/place/entity/DisabilityPlaceCategory.java
src/main/java/Journey/Together/domain/place/repository/DisabilityPlaceCategoryRepository.java
src/main/java/Journey/Together/domain/place/repository/PlaceReviewRepository.java
src/main/java/Journey/Together/domain/place/service/PlaceService.java

- close #76 
관광지 장애 세부유형 설명추가하고 저번에 리뷰 관련 개발 전이라 Null로 처리해놨던 리뷰리스트 추가했습니다.
~/v1/place/{placeId}

[#76] feat: 관광지 장애 세부유형 설명 추가 & 리뷰리스트 추가

---

src/main/java/Journey/Together/domain/place/dto/response/PlaceDetailGuestRes.java
src/main/java/Journey/Together/domain/place/dto/response/PlaceDetailRes.java
src/main/java/Journey/Together/domain/place/entity/Place.java

- close #85 
- ~/v1/place/{placeId}
- ~/v1/place/guest/{placeId}

[Feat/#85 관광지에 전화번호/이메일 정보 추가]

---

src/main/java/Journey/Together/domain/bookbark/controller/BookmarkController.java
src/main/java/Journey/Together/domain/bookbark/dto/PlanBookMarkStateRes.java
src/main/java/Journey/Together/domain/bookbark/service/BookmarkService.java
src/main/java/Journey/Together/global/exception/ErrorCode.java
src/main/java/Journey/Together/global/exception/Success.java

- close #92 
```java
결과 예시 사진 첨부
```
- /v1/bookmark/plan/{planid}

#92 feat : api 구현

---

src/main/java/Journey/Together/domain/member/service/AuthService.java
src/main/java/Journey/Together/global/security/jwt/dto/TokenDto.java

- close #
```java
결과 예시 사진 첨부
```
-

#90 fix : 오류 수정

---

src/main/java/Journey/Together/domain/member/service/MemberService.java

- close #
```java
결과 예시 사진 첨부
```
-

#90 fix : member profile url

---

src/main/java/Journey/Together/domain/plan/entity/Plan.java
src/main/java/Journey/Together/domain/plan/service/PlanService.java

- close #
```java
결과 예시 사진 첨부
```
-

fix : updatePlan 수정

---

src/main/java/Journey/Together/domain/place/repository/PlaceReviewRepository.java
src/main/java/Journey/Together/domain/place/service/PlaceService.java

- close #
place/{placeId}에서 place가 같은 리뷰들 중에서 상위 2개를 뽑아야 하는데 place가 같은 조건이 무시되는 에러 수정
```java
결과 예시 사진 첨부
```
-

fix : placeReivew jpa수정

---

src/main/java/Journey/Together/domain/plan/dto/OpenPlanRes.java
src/main/java/Journey/Together/domain/plan/dto/PlanReviewRes.java
src/main/java/Journey/Together/domain/plan/repository/PlanReviewRepository.java
src/main/java/Journey/Together/domain/plan/service/PlanService.java

planReview에 report filter진행하였습니다. 
exist의 경우에는 report filter를 거치게 하였고 reivew를 보여주는 api에서는 dto에 isReport를 붙여 사용하였습니다
```java
결과 예시 사진 첨부
```
-

fix : report filter to planreview

---

src/main/java/Journey/Together/domain/member/service/AuthService.java
src/main/java/Journey/Together/global/exception/ErrorCode.java
src/main/java/Journey/Together/global/security/kakao/KakaoClient.java
src/main/java/Journey/Together/global/security/kakao/dto/KakaoToken.java

- close #
회원 탈퇴 기능 구현하였습니다
```java
결과 예시 사진 첨부
```
-

feat : kakao 회원탈퇴 기능

---

src/main/java/Journey/Together/domain/member/service/AuthService.java
src/main/java/Journey/Together/domain/plan/entity/PlanReview.java

- close #14 
delete 시 외래 키 제약 조건으로 인한 오류수정
application.yml에서 kakao client-id, client-secret 수정하였습니다
```java
결과 예시 사진 첨부
```
-

#14 fix : 회원 탈퇴 시 delete 오류

---

build.gradle
src/main/java/Journey/Together/domain/member/dto/MemberReq.java
src/main/java/Journey/Together/domain/member/dto/MemberRes.java
src/main/java/Journey/Together/domain/member/service/AuthService.java
src/main/java/Journey/Together/domain/member/service/MemberService.java
src/main/java/Journey/Together/global/security/kakao/dto/KakaoProfile.java

- close #111 
카카오 동의 항목 변경으로 인한 코드 수정
```java
결과 예시 사진 첨부
```
-

fix: 카카오 로그인 이름 데이터 저장 변경

---

build.gradle
src/main/java/Journey/Together/global/config/SecurityConfig.java
src/main/java/Journey/Together/global/config/SwaggerConfig.java

[Feat/#115]: Swagger 설정

---

.github/workflows/CD.yml

- close #
```java
결과 예시 사진 첨부
```
-

#130 fix: cd.yml docker log 확인 위해서 수정

---

.github/workflows/CD.yml

- close #
```java
결과 예시 사진 첨부
```
-

#130 fix: sleep시간 늘리기

---

.github/workflows/CD.yml

fix: CD.yml 수정

---

.github/workflows/CI.yml

- close #
CI.yml이 CD.yml로 중복 코드 되어있어, 수정

fix: CI.yml 수정

---

src/main/java/Journey/Together/global/config/RedisConfig.java

- close #152 
```java
결과 예시 사진 첨부
```
-

 [#152] fix: RedisConfig 수정
